//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.nicktee.redditreader.services;

import java.util.HashMap;
import org.codehaus.jackson.JsonNode;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;

public class IRedditService_
    implements IRedditService
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public IRedditService_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
        rootUrl = "";
    }

    @Override
    public JsonNode getRedditsAsJSONPage(String after, String subreddits) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("subreddits", subreddits);
        urlVariables.put("after", after);
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("http://www.reddit.com/r/{subreddits}/.json?count=25&after={after}"), HttpMethod.GET, requestEntity, JsonNode.class, urlVariables).getBody();
    }

    @Override
    public JsonNode getRedditsAsJSON(String subreddits) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("subreddits", subreddits);
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("http://www.reddit.com/r/{subreddits}/.json"), HttpMethod.GET, requestEntity, JsonNode.class, urlVariables).getBody();
    }

}
